server {
    listen 80;
    server_name _;

    # PROD UI (served from /prod/)
    location /prod/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    # UAT UI (served from /uat/)
    location /uat/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /index.html;
    }

    # Proxy backend APIs - nginx reverse proxy outside this container will route /api/prod/ and /api/uat/ to backend
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://10.10.0.218:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
